#!/bin/bash

echo "Build hook running"

# once dockerhub supports ARG before FROM (upgrade to 1.9)
# docker build --build-arg CODE_VERSION=3.6 -t $DOCKER_REPO:3.6-$CACHE_TAG .
# docker build --build-arg CODE_VERSION=3.5 -t $DOCKER_REPO:3.5-$CACHE_TAG .

echo "Building 3.6..."
docker build -t $DOCKER_REPO:3.6-$CACHE_TAG -f Dockerfile .
echo "Building 3.5..."
docker build -t $DOCKER_REPO:3.5-$CACHE_TAG -f Dockerfile.3.5 .
