#!/bin/bash

docker tag $DOCKER_REPO:3.6-$CACHE_TAG $DOCKER_REPO:latest
docker tag $DOCKER_REPO:3.6-$CACHE_TAG $DOCKER_REPO:3.6
docker tag $DOCKER_REPO:3.5-$CACHE_TAG $DOCKER_REPO:3.5

docker push $DOCKER_REPO
docker push $DOCKER_REPO:3.6-$CACHE_TAG
docker push $DOCKER_REPO:3.6
docker push $DOCKER_REPO:3.5-$CACHE_TAG
docker push $DOCKER_REPO:3.5