#!/bin/bash

VERSION=$(cat VERSION)
echo "Tagging and pushing..."

docker tag $DOCKER_REPO:3.6-$VERSION $DOCKER_REPO:latest
docker tag $DOCKER_REPO:3.6-$VERSION $DOCKER_REPO:3.6
docker tag $DOCKER_REPO:3.5-$VERSION $DOCKER_REPO:3.5

docker push $DOCKER_REPO
docker push $DOCKER_REPO:3.6-$VERSION
docker push $DOCKER_REPO:3.6
docker push $DOCKER_REPO:3.5-$VERSION
docker push $DOCKER_REPO:3.5